#!/usr/bin/env bash

go mod tidy
go fmt ./...

# run linter
golangci-lint run
echo 'Linting done!'

# generate handlebarsjs
go run cmd/handlebarsjs/main.go

# generate json schema
go run cmd/jsonschema/main.go

git add -u
