package main

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

const (
	handlebarsJSURL    = "https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.8/handlebars.min.js"
	handlebarsJSOutput = "pkg/jsruntime/gen/handlebarsjs.gen.go"

	helperJSFile = "pkg/jsruntime/helper.js"
	helperOutput = "pkg/jsruntime/gen/helper.gen.go"
)

//go:generate sh -c "cd ../../ && go run cmd/handlebarsjs/main.go"
func main() {

	// Generate handlebarsjs.gen.go
	genHandlebarJS()

	// Generate helper.gen.go
	genHelper()

}

func genHelper() {
	jsCode, err := os.ReadFile(helperJSFile)
	if err != nil {
		log.Fatal("Error reading file:", err)
	}

	escapedJSCode := strings.ReplaceAll(string(jsCode), "`", "` + \"`\" + `")

	content := fmt.Sprintf("// Code generated by cmd/handlebarsjs/main.go; DO NOT EDIT.\n\npackage gen\n\nconst HelperJS = `%s`\n", escapedJSCode)

	generateFile(helperOutput, content)
}

func genHandlebarJS() {
	resp, err := http.Get(handlebarsJSURL)
	if err != nil {
		log.Fatal("Error fetching HandlebarsJS:", err)
	}
	defer resp.Body.Close()

	jsCode, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal("Error reading response:", err)
	}

	escapedJSCode := strings.ReplaceAll(string(jsCode), "`", "` + \"`\" + `")

	content := fmt.Sprintf("// Code generated by cmd/handlebarsjs/main.go; DO NOT EDIT.\n\npackage gen\n\nconst HandlebarsJS = `%s`\n", escapedJSCode)

	generateFile(handlebarsJSOutput, content)
}

func generateFile(filePath, content string) {
	if err := os.MkdirAll(filepath.Dir(filePath), 0755); err != nil {
		log.Fatal(err)
	}
	err := os.WriteFile(filePath, []byte(content), 0644)
	if err != nil {
		log.Fatal(err)
	}
}
